In [1]:
import numpy as np
from sklearn import metrics

In [2]:
from google.colab import files
uploaded = files.upload()

Saving pima-indians-diabetes.csv to pima-indians-diabetes.csv


In [4]:
raw_data = open("pima-indians-diabetes.csv")
# load the CSV file as a numpy matrix
dataset = np.loadtxt(raw_data, delimiter=",")
print(dataset.shape)
# separate the data from the target attributes
X = dataset[:,0:7]
y = dataset[:,8]
print(X)
print(y)

(768, 9)
[[  6.    148.     72.    ...   0.     33.6     0.627]
 [  1.     85.     66.    ...   0.     26.6     0.351]
 [  8.    183.     64.    ...   0.     23.3     0.672]
 ...
 [  5.    121.     72.    ... 112.     26.2     0.245]
 [  1.    126.     60.    ...   0.     30.1     0.349]
 [  1.     93.     70.    ...   0.     30.4     0.315]]
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0.
 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0.
 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0.
 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1

In [5]:
"""
5. Number of Instances: 768

6. Number of Attributes: 8 plus class 

7. For Each Attribute: (all numeric-valued)
   1. Number of times pregnant
   2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test
   3. Diastolic blood pressure (mm Hg)
   4. Triceps skin fold thickness (mm)
   5. 2-Hour serum insulin (mu U/ml)
   6. Body mass index (weight in kg/(height in m)^2)
   7. Diabetes pedigree function
   8. Age (years)
   9. Class variable (0 or 1)

8. Missing Attribute Values: Yes

9. Class Distribution: (class value 1 is interpreted as "tested positive for
   diabetes")

   Class Value  Number of instances
   0            500
   1            268

10. Brief statistical analysis:

    Attribute number:    Mean:   Standard Deviation:
    1.                     3.8     3.4
    2.                   120.9    32.0
    3.                    69.1    19.4
    4.                    20.5    16.0
    5.                    79.8   115.2
    6.                    32.0     7.9
    7.                     0.5     0.3
    8.                    33.2    11.8
"""

'\n5. Number of Instances: 768\n\n6. Number of Attributes: 8 plus class \n\n7. For Each Attribute: (all numeric-valued)\n   1. Number of times pregnant\n   2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test\n   3. Diastolic blood pressure (mm Hg)\n   4. Triceps skin fold thickness (mm)\n   5. 2-Hour serum insulin (mu U/ml)\n   6. Body mass index (weight in kg/(height in m)^2)\n   7. Diabetes pedigree function\n   8. Age (years)\n   9. Class variable (0 or 1)\n\n8. Missing Attribute Values: Yes\n\n9. Class Distribution: (class value 1 is interpreted as "tested positive for\n   diabetes")\n\n   Class Value  Number of instances\n   0            500\n   1            268\n\n10. Brief statistical analysis:\n\n    Attribute number:    Mean:   Standard Deviation:\n    1.                     3.8     3.4\n    2.                   120.9    32.0\n    3.                    69.1    19.4\n    4.                    20.5    16.0\n    5.                    79.8   115.2\n    6.  

In [6]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
# fit a logistic regression model to the data
model = LogisticRegression(max_iter=1000)
model.fit(X,y)
print(model)
# make predictions
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(y, predicted))
print(metrics.confusion_matrix(y, predicted))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
              precision    recall  f1-score   support

         0.0       0.79      0.89      0.84       500
         1.0       0.73      0.56      0.64       268

    accuracy                           0.77       768
   macro avg       0.76      0.73      0.74       768
weighted avg       0.77      0.77      0.77       768

[[444  56]
 [117 151]]


In [7]:
# Knn- classification
# k-Nearest Neighbor Classification
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X,y)
print(model)
# make predictions
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(y, predicted))
print(metrics.confusion_matrix(y, predicted))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')
              precision    recall  f1-score   support

         0.0       0.82      0.90      0.86       500
         1.0       0.77      0.63      0.69       268

    accuracy                           0.80       768
   macro avg       0.79      0.77      0.78       768
weighted avg       0.80      0.80      0.80       768

[[448  52]
 [ 98 170]]


In [8]:
# import Keras libraries
from keras.models import Sequential
from keras.layers import Dense
import numpy
# fix random seed for reproducibility
numpy.random.seed(7)

In [10]:
# load pima indians dataset
dataset = numpy.loadtxt("pima-indians-diabetes.csv", delimiter=",")
# split into input (X) and output (Y) variables
X = dataset[:,0:8]
Y = dataset[:,8]

In [11]:
# create model
# input_dim = 8 for 8 input variables
# Specify the neural network model sequentially
model = Sequential()
model.add(Dense(20, input_dim=8, activation='relu')) # 12 neurons
model.add(Dense(10, activation='relu')) # 8 neurons
model.add(Dense(1, activation='sigmoid'))
# Sigmoid to get an output between 0 and 1

In [12]:
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Fit the model
model.fit(X, Y, epochs=100, batch_size=10) # 500
# epochs = number of iterations

Epoch 1/100
77/77 [==============================] - 1s 1ms/step - loss: 13.0655 - accuracy: 0.6082
Epoch 2/100
77/77 [==============================] - 0s 1ms/step - loss: 1.8748 - accuracy: 0.6100
Epoch 3/100
77/77 [==============================] - 0s 1ms/step - loss: 1.2302 - accuracy: 0.5953
Epoch 4/100
77/77 [==============================] - 0s 1ms/step - loss: 0.7827 - accuracy: 0.6655
Epoch 5/100
77/77 [==============================] - 0s 1ms/step - loss: 0.7488 - accuracy: 0.6400
Epoch 6/100
77/77 [==============================] - 0s 1ms/step - loss: 0.6854 - accuracy: 0.6671
Epoch 7/100
77/77 [==============================] - 0s 1ms/step - loss: 0.6678 - accuracy: 0.6634
Epoch 8/100
77/77 [==============================] - 0s 1ms/step - loss: 0.6446 - accuracy: 0.6794
Epoch 9/100
77/77 [==============================] - 0s 1ms/step - loss: 0.6878 - accuracy: 0.6319
Epoch 10/100
77/77 [==============================] - 0s 1ms/step - loss: 0.6407 - accuracy: 0.6891
Epoch 11

In [13]:
# evaluate the model
scores = model.evaluate(X, Y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
print(scores)

24/24 [==============================] - 0s 988us/step - loss: 0.4828 - accuracy: 0.7656

accuracy: 76.56%
[0.4827633798122406, 0.765625]


In [14]:
row1 = [6,148,72,35,0,33.6,0.627,50] # output =1
row2 = [1,85,66,29,0,26.6,0.351,31] # output = 0
row3 = [8,183,64,0,0,23.3,0.672,32] # output = 1
row4 = [1,89,66,23,94,28.1,0.167,21] # output = 0
row5 = [0,137,40,35,168,43.1,2.288,33] # output = 1
five_rows = numpy.array([row1,row2,row3,row4,row5])

In [15]:
model.predict(five_rows, batch_size=5)

array([[0.7429754 ],
       [0.09597629],
       [0.966216  ],
       [0.08568591],
       [0.67667097]], dtype=float32)