In [ ]:
import tensorflow as tf
from sklearn.datasets import load_iris
data = load_iris()

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.33, random_state=42)

In [ ]:
# Four inputs (Sepal length, Sepal Width, Petal length, Petal Width)
# 1st hidden layer = 10 neurons; activation=relu
# Output layer = 3 neurons; activation = softmax 
# softmax == The the elements of the output vector are in range (0, 1) and sum to 1.

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(10, activation=tf.nn.relu),
  tf.keras.layers.Dense(3, activation=tf.nn.softmax)
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=300)

Epoch 1/300
4/4 [==============================] - 0s 2ms/step - loss: 1.9651 - accuracy: 0.3400
Epoch 2/300
4/4 [==============================] - 0s 2ms/step - loss: 2.0363 - accuracy: 0.3300
Epoch 3/300
4/4 [==============================] - 0s 2ms/step - loss: 1.5937 - accuracy: 0.2900
Epoch 4/300
4/4 [==============================] - 0s 1ms/step - loss: 1.6539 - accuracy: 0.2500
Epoch 5/300
4/4 [==============================] - 0s 1ms/step - loss: 1.7058 - accuracy: 0.1800
Epoch 6/300
4/4 [==============================] - 0s 2ms/step - loss: 1.7605 - accuracy: 0.1400
Epoch 7/300
4/4 [==============================] - 0s 1ms/step - loss: 1.5080 - accuracy: 0.1200
Epoch 8/300
4/4 [==============================] - 0s 1ms/step - loss: 1.5477 - accuracy: 0.0900
Epoch 9/300
4/4 [==============================] - 0s 1ms/step - loss: 1.5745 - accuracy: 0.0900
Epoch 10/300
4/4 [==============================] - 0s 1ms/step - loss: 1.6028 - accuracy: 0.0800
Epoch 11/300
4/4 [===========

In [ ]:
model.evaluate(x_test, y_test) # reports loss and accuracy

2/2 [==============================] - 0s 4ms/step - loss: 0.2936 - accuracy: 0.9600


[0.2935786247253418, 0.9599999785423279]

In [ ]:
from sklearn import metrics

In [ ]:
predicted = model.predict(x_test)
print(predicted)
print(type(predicted))
predicted_list = predicted.tolist()

[[7.7223955e-03 5.9884757e-01 3.9343005e-01]
 [9.9017930e-01 7.5910809e-03 2.2295942e-03]
 [2.2886660e-04 2.3069257e-01 7.6907861e-01]
 [1.1741489e-02 6.0258269e-01 3.8567579e-01]
 [5.1252213e-03 5.6055528e-01 4.3431947e-01]
 [9.8050529e-01 1.5300333e-02 4.1944408e-03]
 [4.2783633e-02 7.3148876e-01 2.2572754e-01]
 [4.4876854e-03 4.2680103e-01 5.6871128e-01]
 [4.1108211e-03 4.5862782e-01 5.3726131e-01]
 [2.1017386e-02 6.9336164e-01 2.8562093e-01]
 [6.2861461e-03 4.9129140e-01 5.0242239e-01]
 [9.7401410e-01 2.0305105e-02 5.6807343e-03]
 [9.9203283e-01 6.2500881e-03 1.7169632e-03]
 [9.7469473e-01 1.9688219e-02 5.6170179e-03]
 [9.9495065e-01 3.8929698e-03 1.1564579e-03]
 [1.3600594e-02 6.3813818e-01 3.4826124e-01]
 [1.6007758e-03 3.0291364e-01 6.9548553e-01]
 [1.7680824e-02 6.7061484e-01 3.1170446e-01]
 [1.1620534e-02 6.0921544e-01 3.7916401e-01]
 [1.6376224e-03 2.9481480e-01 7.0354754e-01]
 [9.7538382e-01 1.9038305e-02 5.5779004e-03]
 [7.4148634e-03 5.0991219e-01 4.8267296e-01]
 [9.795912

In [ ]:
predicted_012 = [row.index(max(row)) for row in predicted_list]
print(predicted_012)

[1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2]


In [ ]:
print(y_test)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0 1 2 2 1 2]


In [ ]:
print(metrics.classification_report(y_test, predicted_012))
print(metrics.confusion_matrix(y_test, predicted_012))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50

[[19  0  0]
 [ 0 14  1]
 [ 0  1 15]]


In [ ]:
for layer in model.layers: 
  print(layer.get_weights())

[array([[ 0.10146976,  0.19250157,  0.06273371,  0.58852357,  0.3508557 ,
         0.12456144,  0.14462548, -0.04464033, -0.6075637 , -0.01059525],
       [-0.13863903,  0.43827268, -0.5879739 , -0.1771375 , -0.41595638,
         0.13442542,  0.5148898 ,  0.97831345,  0.3468851 ,  0.858701  ],
       [-0.40445954,  0.1960729 , -0.45745236,  0.46379533, -0.56825376,
         0.5146868 , -0.3380123 , -0.42603257,  0.48712754, -0.48845994],
       [-0.4910847 ,  0.44012618,  0.33859122, -0.07473494, -0.42815304,
         0.05714549,  0.42909327, -0.10930354, -0.6525929 , -0.6889816 ]],
      dtype=float32), array([ 0.        , -0.26263335,  0.        ,  0.26738548,  0.        ,
       -0.19669813, -0.17224851,  0.48665598,  0.        ,  0.24376033],
      dtype=float32)]
[array([[ 4.3330848e-01,  4.9301553e-01, -3.1184959e-01],
       [-2.6468879e-01, -4.3819231e-01,  4.2628375e-01],
       [-5.3019637e-01,  6.3304150e-01, -4.7541839e-01],
       [-4.2027756e-04,  6.7233092e-01,  6.151194

In [ ]:
"""
We have four inputs: SL, SW, PL, and PW
2) Layer 1 is 10 neurons
2a) So, weight and bias from each of the four inputs to each of the 10 neurons

Now, from 10 hidden layer neurons, we have 3 outputs.
This is the second numpy matrix
connection from each of the 10 neurons to the output.
the equation for the first connection:
"""

In [ ]:
load_iris()

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [ ]:
print(tf.__version__)

2.2.0-rc1
